PlayerBitmap            dg ..xxxxxxxxx.....
                        dg .x.........x....
                        dg .x..x...x..x....
                        dg ..xxxxxxxxx.....
                        dg ....xxxxx.......
                        dg ..xxx.x.xxx.....
                        dg .xx.x...x.xx....
                        dg .xx.x.x.x.xx....
                        dg .xx.xxxxx.xx....
                        dg ...xxx.xxx......
                        dg ...xxx.xxx......
                        dg ...xxx.xxx......

                        dg ......xxxxxxxxx.
                        dg .....x.........x
                        dg .....x..x...x..x
                        dg ......xxxxxxxxx.
                        dg ........xxxxx...
                        dg ......xxx.x.xxx.
                        dg .....xx.x...x.xx
                        dg .....xx.x.x.x.xx
                        dg .....xx.xxxxx.xx
                        dg .......xxx.xxx..
                        dg .......xxx.xxx..
                        dg .......xxx.xxx..

BulletBitmap            dg ................
                        dg ................
                        dg ................
                        dg ....xxxx........
                        dg ...xxxxxx.......
                        dg ...xx..xx.......
                        dg ...xx..xx.......
                        dg ...xxxxxx.......
                        dg ....xxxx........
                        dg ................
                        dg ................
                        dg ................

                        dg ................
                        dg ................
                        dg ................
                        dg ........xxxx....
                        dg .......xxxxxx...
                        dg .......xx..xx...
                        dg .......xx..xx...
                        dg .......xxxxxx...
                        dg ........xxxx....
                        dg ................
                        dg ................
                        dg ................

BotBitmap               dg ...xxxxxx.......
                        dg ..xx....xx......
                        dg ...xxxxxx.......
                        dg ....x..x........
                        dg xxxx....xxxx....
                        dg x..........x....
                        dg x.x......x.x....
                        dg xxx.x..x.xxx....
                        dg ...x....x.......
                        dg ..x..xx..x......
                        dg .xxxx..xxxx.....
                        dg .xxxx..xxxx.....

                        dg .......xxxxxx...
                        dg ......xx....xx..
                        dg .......xxxxxx...
                        dg ........x..x....
                        dg ....xxxx....xxxx
                        dg ....x..........x
                        dg ....x.x......x.x
                        dg ....xxx.x..x.xxx
                        dg .......x....x...
                        dg ......x..xx..x..
                        dg .....xxxx..xxxx.
                        dg .....xxxx..xxxx.

