PlayerBitmap            dg .xxxxx.xxxxx....
                        dg .x...x.x...x....
                        dg .x.xx...xx.x....
                        dg .xxx.xxx.xxx....
                        dg ....xxxxx.......
                        dg ..xxx.x.xxx.....
                        dg .xx.x...x.xx....
                        dg .xx.x.x.x.xx....
                        dg .xx.xxxxx.xx....
                        dg ...xxx.xxx......
                        dg ...xxx.xxx......
                        dg ...xxx.xxx......

                        dg .....xxxxx.xxxxx
                        dg .....x...x.x...x
                        dg .....x.xx...xx.x
                        dg .....xxx.xxx.xxx
                        dg ........xxxxx...
                        dg ......xxx.x.xxx.
                        dg .....xx.x...x.xx
                        dg .....xx.x.x.x.xx
                        dg .....xx.xxxxx.xx
                        dg .......xxx.xxx..
                        dg .......xxx.xxx..
                        dg .......xxx.xxx..

BulletBitmap            dg ................
                        dg ................
                        dg ................
                        dg ....xxxx........
                        dg ...xxxxxx.......
                        dg ...xx..xx.......
                        dg ...xx..xx.......
                        dg ...xxxxxx.......
                        dg ....xxxx........
                        dg ................
                        dg ................
                        dg ................

                        dg ................
                        dg ................
                        dg ................
                        dg ........xxxx....
                        dg .......xxxxxx...
                        dg .......xx..xx...
                        dg .......xx..xx...
                        dg .......xxxxxx...
                        dg ........xxxx....
                        dg ................
                        dg ................
                        dg ................

