
                        org $f000

TestBitmap              equ *

                        dg .xx......xx.....
                        dg x..x....x..x....
                        dg x..x....x..x....
                        dg .xx......xx.....
                        dg .....xx.........
                        dg ....xxxx........
                        dg ....xxxx........
                        dg .....xx.........
                        dg .xx......xx.....
                        dg x..x....x..x....
                        dg x..x....x..x....
                        dg .xx......xx.....

                        dg .....xx......xx.
                        dg ....x..x....x..x
                        dg ....x..x....x..x
                        dg .....xx......xx.
                        dg .........xx.....
                        dg ........xxxx....
                        dg ........xxxx....
                        dg .........xx.....
                        dg .....xx......xx.
                        dg ....x..x....x..x
                        dg ....x..x....x..x
                        dg .....xx......xx.

